services:
    db:
        image: postgres:15
        volumes:
            - './data/joplin-db:/var/lib/postgresql/data'
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - DB_CLIENT=pg
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - APP_BASE_URL=http://192.168.1.42:22300
            - MAILER_ENABLED=1
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_SECURITY=starttls
            - MAILER_AUTH_USER=${MAILER_AUTH_USER}
            - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
            - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
            - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}

