services:
  mysql:
    container_name: 'mysql'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      # MYSQL_DATABASE: ""
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - './data/mysql:/var/lib/mysql'
