services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
