#!/bin/bash

# Set the default port
port=${1:-9910}

# Create the proxy configuration text
proxy_text="export ALL_PROXY=\"socks5h://127.0.0.1:$port\"\nexport all_proxy=\"socks5h://127.0.0.1:$port\"\nexport http_proxy=\"http://127.0.0.1:$port\"\nexport https_proxy=\"http://127.0.0.1:$port\"\nexport HTTP_PROXY=\"http://127.0.0.1:$port\"\nexport HTTPS_PROXY=\"http://127.0.0.1:$port\"\nexport no_proxy=\"localhost,127.0.0.1,::1\"\nexport NO_PROXY=\"localhost,127.0.0.1,::1\""

# Copy the text to the clipboard
echo -e "$proxy_text" | xclip -selection clipboard

echo "Proxy settings have been copied to the clipboard for port $port."
