#!/usr/bin/env bash

exec env \
  ALL_PROXY="socks5h://127.0.0.1:8900" \
  all_proxy="socks5h://127.0.0.1:8900" \
  http_proxy="http://127.0.0.1:8900" \
  https_proxy="http://127.0.0.1:8900" \
  HTTP_PROXY="http://127.0.0.1:8900" \
  HTTPS_PROXY="http://127.0.0.1:8900" \
  no_proxy="localhost,127.0.0.1,::1" \
  NO_PROXY="localhost,127.0.0.1,::1" \
  codex "$@"
