#!/bin/bash

eval "$(ssh-agent -s)"
for key in ~/.ssh/id_*; do
    #ssh-add -t 86400 "$key" 2>/dev/null
    echo "Disable password for $key"
    ssh-keygen -p -f "$key"
    ssh-keygen -y -f "$key" > /dev/null
done
