#!/bin/bash

SCRIPTS_DIR="$HOME/scripts"
SRC_DIR="$SCRIPTS_DIR/src"
export LIBS_DIR="$SCRIPTS_DIR/libs"

add_to_path_if_missing() {
    [ -d "$1" ] || return 0

    case ":$PATH:" in
        *":$1:"*) ;; # already in PATH
        *) PATH="$PATH:$1" ;;
    esac
}

# Script folders
add_to_path_if_missing "$SRC_DIR"
add_to_path_if_missing "$SRC_DIR/file"
add_to_path_if_missing "$SRC_DIR/dotnet"
add_to_path_if_missing "$SRC_DIR/bale"
add_to_path_if_missing "$SRC_DIR/docker"
add_to_path_if_missing "$SRC_DIR/git"
add_to_path_if_missing "$SRC_DIR/media"
add_to_path_if_missing "$SRC_DIR/proxy"
add_to_path_if_missing "$SRC_DIR/s3"
add_to_path_if_missing "$SRC_DIR/tor"
add_to_path_if_missing "$SRC_DIR/translate"
add_to_path_if_missing "$SRC_DIR/gh"
add_to_path_if_missing "$SRC_DIR/backups"
add_to_path_if_missing "$SRC_DIR/ssh"
add_to_path_if_missing "$SRC_DIR/icons"
add_to_path_if_missing "$SRC_DIR/gpg"
add_to_path_if_missing "$SRC_DIR/codex"
add_to_path_if_missing "$SRC_DIR/virgool"
add_to_path_if_missing "$SRC_DIR/mirrors"
add_to_path_if_missing "$SRC_DIR/video"
add_to_path_if_missing "$SRC_DIR/json"
add_to_path_if_missing "$SRC_DIR/agent"
add_to_path_if_missing "$SRC_DIR/archive"
add_to_path_if_missing "$SRC_DIR/desktop"
add_to_path_if_missing "$SRC_DIR/dev"
add_to_path_if_missing "$SRC_DIR/network"
add_to_path_if_missing "$SRC_DIR/security"
add_to_path_if_missing "$SRC_DIR/system"
add_to_path_if_missing "$SRC_DIR/utils"
add_to_path_if_missing "$SRC_DIR/web"
add_to_path_if_missing "$SRC_DIR/npm"

export PATH

cd-where() {
    local target=""

    target=$(command cd-where --print "$@") || return $?
    builtin cd -- "$target"
}
